spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/minicommerce}
    username: ${SPRING_DATASOURCE_USERNAME:minicommerce}
    password: ${SPRING_DATASOURCE_PASSWORD:minicommerce}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
