name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: minicommerce
          POSTGRES_PASSWORD: minicommerce
          POSTGRES_DB: minicommerce
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U minicommerce -d minicommerce"
          --health-interval=5s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build & Test
        working-directory: order-service
        run: ./gradlew --no-daemon clean build test

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        working-directory: order-service
        run: docker build -t mini/order-service:${{ github.sha }} .
      # TODO: Enable pushing to GHCR or Docker Hub
      # - name: Login to GHCR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push
      #   run: docker tag mini/order-service:${{ github.sha }} ghcr.io/<your-org>/order-service:${{ github.sha }} && docker push ghcr.io/<your-org>/order-service:${{ github.sha }}
